name: Terraform Apply

on:
  push:
    branches:
      - main
      - staging

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.0 

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: list dirictiry
      run: ls -ax
      
    - name: pwd list
      run: pwd
      
    - name: cd Final-lab_terraform
      run: cd ~/work/final-lab/final-lab/terraform/

    - name: list current directory
      run: ls -ax

    - name: pwd current directory
      run: pwd
      
    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      run: cd ~/work/final-lab/final-lab/terraform/ | terraform plan

    - name: Terraform Apply
      run: cd ~/work/final-lab/final-lab/terraform/ | terraform apply -auto-approve
